# Generated by Django 4.1.4 on 2022-12-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoself', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-12-08'),
            preserve_default=False,
        ),
    ]
